### ISSUE TITLE
App\Sheet Thumbnail broken after updating the app from repo

### ISSUE THREAD

**Issue by camara-raf** [gitoqlik/helpdesk#8]
Qlik Sense Nov 2019
Actions to replicate the issue:
1) Deploy the app that have thumbnails
![image](https://user-images.githubusercontent.com/31748282/96306563-e2a35780-0fcd-11eb-8637-79af74f16753.png)
![image](https://user-images.githubusercontent.com/31748282/96307049-f00d1180-0fce-11eb-9be6-3251cf66ef05.png)

2) Commit a change to the main branch
![image](https://user-images.githubusercontent.com/31748282/96306669-1ed6b800-0fce-11eb-813e-4378c7d5d979.png)

3) Update the a second branch with the changes from the main branch
![image](https://user-images.githubusercontent.com/31748282/96306730-40d03a80-0fce-11eb-84c0-da9666b6523f.png)

4) Update the app with the latest commit (Update and lost local changes [Note: No local changes were done just a data refresh])
![image](https://user-images.githubusercontent.com/31748282/96306798-60676300-0fce-11eb-9fd9-0244cac64974.png)
![image](https://user-images.githubusercontent.com/31748282/96306822-6d845200-0fce-11eb-86b9-7f3ca4241c78.png)

5) Images are now broken
![image](https://user-images.githubusercontent.com/31748282/96307012-de2b6e80-0fce-11eb-937e-8fb306455742.png)

**Comment by shatzibitten** [comment]
@camara-raf fixed in 1.5.9. Please check it

**Comment by camara-raf** [comment]
I still have the same issues (I checked that my extension is on 1.5.9). I deleted the second branch (QA branch) and kept just the main branch in the repository. Then I deployed a new app/branch, committed a change in the main, and updated the second branch (QA branch). The thumbnails broke again. Do I need to re-create the repo to fix the issue?

**Comment by shatzibitten** [comment]
@camara-raf could you please check it in the actual version?

**Comment by camara-raf** [comment]
Issue fixed, thank you.
